//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PETS()
        {
            this.ANNOUNCEMENTS = new HashSet<ANNOUNCEMENTS>();
        }
    
        public int petID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string petClass { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string photoURL { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> vetID { get; set; }
        public Nullable<bool> approvalSituation { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNOUNCEMENTS> ANNOUNCEMENTS { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual VETS VETS { get; set; }
    }
}
